FROM rayproject/ray:2.53.0-aarch64

# Dependencies required for training
RUN pip3 install --no-cache-dir torch torchvision lightning

USER root
RUN mkdir -p /app

# Set the working directory
WORKDIR /app

COPY tune/ /app/tune
